//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cities_Manager_Pm2d5In
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_Pm25In
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Code { get; set; }
    }
}
