//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESCDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int index { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string aqi { get; set; }
        public string rank { get; set; }
        public Nullable<int> pm2d5 { get; set; }
        public Nullable<int> pm10 { get; set; }
        public Nullable<int> so2 { get; set; }
        public Nullable<double> co { get; set; }
        public Nullable<int> no2 { get; set; }
        public Nullable<int> o3_8 { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string range { get; set; }
    }
}
